### ISSUE TITLE
TODO：移植部分 HTTPS-Everywhere 规则

### ISSUE THREAD

**Issue by ivysrono** [ivysrono/URLRedirectorRules#1]
搭配 smarthttps，抛弃 HTTPS-Everywhere 后还需要解决部分资源重定向的问题。

# 阿里

- [ ] [Taobao.com.xml](https://github.com/EFForg/https-everywhere/blob/master/src/chrome/content/rules/Taobao.com.xml)
- [ ] [Taobao_CDN.com.xml](https://github.com/EFForg/https-everywhere/blob/master/src/chrome/content/rules/Taobao_CDN.com.xml)
- [ ] [TbCDN.cn.xml](https://github.com/EFForg/https-everywhere/blob/master/src/chrome/content/rules/TbCDN.cn.xml)

# 网易

- [ ] [126.net.xml](https://github.com/EFForg/https-everywhere/blob/master/src/chrome/content/rules/126.net.xml)
- [ ] [NetEase.com.xml](https://github.com/EFForg/https-everywhere/blob/master/src/chrome/content/rules/NetEase.com.xml)

# 新浪

- [ ] [Sinaimg.cn.xml](https://github.com/EFForg/https-everywhere/blob/master/src/chrome/content/rules/Sinaimg.cn.xml)
